apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: test-jms-apache-artemis-sink-native
  annotations:
    trait.camel.apache.org/quarkus.package-type: native
    trait.camel.apache.org/builder.properties: quarkus.native.native-image-xmx=3g
spec:
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: jms-apache-artemis-sink-mod
    properties:
      brokerURL: tcp://ex-aao-hdls-svc.activemq-artemis-operator.svc.cluster.local:61616
      destinationName: bidule
  source:
    properties: {}
    uri: knative:channel/chf42?kind=InMemoryChannel
  steps:
  - ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: log-sink 
